apiVersion: batch/v1
kind: Job
metadata:
  name: pst-cypress-tests
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 900
  template:
    metadata:
      labels:
        app: pst-cypress-tests
    spec:
      restartPolicy: Never
      containers:
        - name: cypress
          image: europe-west1-docker.pkg.dev/project-2e1e6c1d-528d-4a3a-803/toolshop/cypress-k8s:latest
          resources:
            requests:
              cpu: "1000m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "3Gi"
          imagePullPolicy: Always
          env:
            - name: BASE_URL
              value: "http://pst-web:80"
            - name: MYSQL_HOST
              value: pst-db
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: pst-db-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pst-db-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: pst-db-secret
                  key: MYSQL_DATABASE
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: pst-test-secret
                  key: SLACK_WEBHOOK_URL
            - name: ADMIN_USER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pst-test-secret
                  key: ADMIN_USER_EMAIL
            - name: ADMIN_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pst-test-secret
                  key: ADMIN_USER_PASSWORD
            - name: USER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pst-test-secret
                  key: USER_EMAIL
            - name: USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pst-test-secret
                  key: USER_PASSWORD
            - name: TEST_NAME
              value: "CypressTests"
            - name: CYPRESS_VIDEO
              value: "false"
          volumeMounts:
            - name: cypress-artifacts
              mountPath: /artifacts
      volumes:
        - name: cypress-artifacts
          emptyDir: {}
