name: Cypress Tests

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test:all -- --browser chrome
        env:
            ADMIN_USER_EMAIL: ${{ secrets.ADMIN_USER_EMAIL }}
            ADMIN_USER_PASSWORD: ${{ secrets.ADMIN_USER_PASSWORD }}
            USER_EMAIL: ${{ secrets.USER_EMAIL }}
            USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
            BASE_URL: ${{ secrets.BASE_URL }}